[tool.poetry]
name = "poetry-esercizio"
version = "0.1.0"
description = ""
authors = ["Daniela <danpot@alum.us.es>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
